plugins {
    id 'java'
}

dependencies {
    implementation 'org.jmonkeyengine:jme3-core:3.8.1-stable'
    implementation 'org.jmonkeyengine:jme3-jogg:3.8.1-stable'  // ← было jme3-ogg


    // ===== Убрали старую JitPack версию, оставили одну совместимую пару =====
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'com.simsilica:lemur-proto:1.13.0'

    implementation 'org.json:json:20230227'
    implementation 'com.google.code.gson:gson:2.13.2'
    implementation 'com.github.stephengold:Minie:8.0.0'
}

sourceSets {
    main {
        resources {
            srcDirs = ['src/main/resources']
        }
    }
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}