plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.0.13'
}

javafx {
    version = "21"
    modules = [ 'javafx.controls' ]
}

dependencies {
    implementation project(':core')
    implementation 'org.jmonkeyengine:jme3-desktop:3.6.1-stable'
    implementation 'org.jmonkeyengine:jme3-lwjgl:3.6.1-stable'
    implementation 'org.jmonkeyengine:jme3-plugins:3.6.1-stable'

implementation 'org.openjfx:javafx-controls:21'
    implementation 'org.openjfx:javafx-graphics:21'
}

application {
    mainClass = 'com.mygame.DesktopLauncher'
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

tasks.withType(AbstractArchiveTask) {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}